### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by Rivendile** [aravindsrinivas/curl_rainbow#2]
When I run the code on TITAN RTX with python3.6, CUDA 10.0.130, pytorch 1.4.0, I got the error like this:
  File "curl_rainbow/agent.py", line 74, in act
    return (a * self.support).sum(2).argmax(1).item()
RuntimeError: CUDA error: an illegal memory access was encountered

But I can run this code on cpu. Does anyone know what happens here?

**Comment by teslacool** [comment]
You should instantiate the [layernorm](https://github.com/aravindsrinivas/curl_rainbow/blob/40bf738b9355e8ee9e4641fd5951d451f1e18974/model.py#L90) in \_\_init\_\_ function.

**Comment by mazpie** [comment]
You can also change 

`h = nn.LayerNorm(h.shape[1])(h)`

into 

`h = nn.LayerNorm(h.shape[1]).cuda()(h)`

**Comment by aravindsrinivas** [comment]
Thanks for the suggestions. Closing since code was provided as-is; and is not going to be updated.
