### ISSUE TITLE
About Frame skip

### ISSUE THREAD

**Issue by binmom** [aravindsrinivas/curl_rainbow#3]
In this CURL original paper, it says atari benchmark use 4 frameskip.

But, in this code, default code has 0 frameskip.

Is there something point that I miss?

**Comment by aravindsrinivas** [comment]
The frame skip was implemented by @Kaixhin in a different way, with an explicit for loop. 

https://github.com/aravindsrinivas/curl_rainbow/blob/master/env.py#L66
