### ISSUE TITLE
can't reproduce on pong and hero

### ISSUE THREAD

**Issue by noahcao** [aravindsrinivas/curl_rainbow#4]
I tried the code with default parameter you set.

But I can't reproduce the reward on pong and hero as reported in the paper. To be precise, the reward is ~-20 vs -16.5 on pong and ~3000 vs ~6000 on hero.

![1604491601803](https://user-images.githubusercontent.com/17743251/98109895-49cf7000-1ed9-11eb-8ff6-2176ce27681e.jpg)

![1604491647592](https://user-images.githubusercontent.com/17743251/98109997-69669880-1ed9-11eb-9626-7daf98555978.jpg)

Do you have any idea why this happened? I simply used the command:

> python main.py --game pong/hero

**Comment by aravindsrinivas** [comment]
Please run with more seeds. You can check Table 6 and Table 7 in the paper which has scores reported for 20 different seeds per game.
