### ISSUE TITLE
About the evaluation choice

### ISSUE THREAD

**Issue by Cohencohenchen** [aravindsrinivas/curl_rainbow#5]
Hi Aravind,

I like your work very much! But I just have one question about the evaluation, when I directly run your code in the game battle zone, sometimes the best performance is not in the end but in the middle, and the performance in the end could be worse and couldn't reach the scores mentioned in the paper. Did you use the best score ever, or only the score in the end in the evaluation? Thank you very much!

**Comment by aravindsrinivas** [comment]
The best score during the course of training is reported.
